# Generated by Django 3.2 on 2021-05-12 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20210512_1551'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('username', 'account_type')},
        ),
    ]
